[theme]
base = "dark"
primaryColor = "#66d9ff"
backgroundColor = "#05080f"
secondaryBackgroundColor = "#080f1a"
textColor = "#eaf2ff"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
